console.log('se procedera a un cambio de nombre');
console.log('Este fichero se añadirá al área de preparación');
console.log('esto se añadirá al merge');
console.log('esto se añadirá al segundo merge');
console.log('esto se intentará añadir al tercer merge en la rama master');
console.log('esto se intentará añadir al tercer merge en la rama adarra');
console.log('para despues hacer fetch de esto');
console.log('adarberrian');
console.log('adarberrian oraindik');
console.log('adarberrian birrantolatu aurretik');
console.log('actualizando desde otro repositorio');
console.log('actualizando desde otro repositorio');
console.log('commit pa tag');
